---
- name: Test / Generate random passwords with specifities
  # Define global var from generated local vars v
  set_fact:
      my_username: '{{ username_alias }}'
      my_pass: '{{ password_alias }}'
  vars:
    username_alias: "{{ lookup('password', './wp-username.txt length=50 chars=ascii_letters,digits') }}"
    password_alias: "{{ lookup('password', './wp-password.txt length=50 chars=ascii_letters,digits,!,?,%,^,&,)') }}"

# Re-use var, password isn't re-created every time
- debug:
    msg: '{{ my_username }}'
- debug:
    msg: '{{ my_pass }}'
...