---
- name: Test / Generate random passwords with a prefix
  # Define global var from generated local vars v
  set_fact:
      # Be careful as password in file won't be prefixed
      prefix_my_pass: 'da_prefix_{{ prefix_password_alias }}'
  vars:
    prefix_password_alias: "{{ lookup('password', './prefixed-password.txt length=50 chars=ascii_letters,digits,!,?,%,^,&,)') }}"

# Re-use var, password isn't re-created every time
- debug:
    msg: '{{ prefix_my_pass }}'
...