---
- name: Installation d'un truc avec user différent de root
  hosts: likorne
  remote_user: '{{ my_remote_user }}'
  become: yes
  vars_files:
  - vars/main.yml

  # Commandes ansible classiques
  tasks:
    - name: Installation de git
      apt: name=git update_cache=yes
...