---
- name: Basic tasks
  hosts: likorne
  remote_user: ubuntu
  become: yes
  vars_files:
  - vars/main.yml

  roles:
    # Install desired packages
    # - utils
    # Create a new user
    # - user
    # Install & lunch a service (ex: nginx)
    # - service
    # Manage folders and files
    # - foldersAndFiles
    # Edit line in file
    - editLineInFile
    
...