---
- name: Basic tasks
  hosts: likorne
  remote_user: ubuntu
  become: yes
  vars:
    user: volibear
  vars_files:
  - vars/main.yml

  tasks:
    ### Packages ###
    - name: Ubuntu 1 package installation
      apt: name=git update_cache=yes

    # DEPRECATED
    #- name: Ubuntu multiple package installations
    #  apt: name={{ item }} update_cache=yes
    #  with_items:
    #    - git
    #    - vim
    #    - htop
    #    - zsh

    # https://docs.ansible.com/ansible/latest/modules/apt_module.html#apt-module
    - name: Ubuntu multiple package installations
      apt:
        cache_valid_time: 3600
        name: ['git', 'vim', 'htop', 'zsh']
        update_cache: yes
        state: latest

    - name: Upgrade all packages to the latest version
      apt:
        name: "*"
        state: latest

    - name: Remove useless packages from the cache
      apt:
        autoclean: yes

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes

  roles:
    - user
...