## https://hub.docker.com/_/traefik
# KO

# Docker configuration backend
providers:
    docker:
      defaultRule: "Host(`{{ trimPrefix `/` .Name }}.docker.localhost`)"
  
  # API and dashboard configuration
  api:
    insecure: true