version: '3.7'

services:
  helloworldDeux:
    deploy:
      labels:
        # Tell Traefik to get the contents provided by this service using that shared network.
        - "traefik.docker.network=traefik-public"
        # Allow internet exposition (publish on port 80)
        - "traefik.enable=true"
        
        # Specify entrypoint
        - "traefik.http.routers.grafanaMasamuneFr_HelloworldDeux_Router.entrypoints=web"
        # On which url ? Reverse proxy regexp
        - "traefik.http.routers.grafanaMasamuneFr_HelloworldDeux_Router.rule=Host(`grafana.masamune.fr`)"
        # Use the service specifying the internal port
        - "traefik.http.routers.grafanaMasamuneFr_HelloworldDeux_Router.service=grafanaMasamuneFr_HelloworldDeux_Service"
        
        # Create a service specifying the internal port
        # - "traefik.http.services.grafanaMasamuneFr_HelloworldDeux_Service.loadbalancer.server.port=8080" # NO
        - "traefik.http.services.grafanaMasamuneFr_HelloworldDeux_Service.loadbalancer.server.port=80"
    image: tutum/hello-world:latest
    networks:
      # Connect to traefik dedicated overlay network, allow reverse proxy
      - traefik-public
    # Optionnal / Specify a FREE external port
    # ports:
    #   - "15000:80"

networks:
  traefik-public:
    # Connect to an existing network
    external: true