version: "3.7"

# Issues & fixes
#   Access to docker socket is a security risk
#   > Grant access through a proxy container
#   TODO: > read only ?

#   Privileged is mandatory to access docker socket, and is also a security risk
#   > Only the proxy container is privileged
#     Priviledged incompatible with user namespace remap.
#     > Force disable user namespace remap on proxy
#       userns_mode: "host" not compatible with docker stack
#       > Will be used through docker compose
#       > Also enable the use of a bridge network

#   Stack only allow overlay networks > security risk
#   > Use docker compose for Traefik & proxy, and set a custom bridge network
#     > non attachable
#     TODO: > encrypted

services:
  dockersocketproxy:
    environment:
      # Authorize access
      NETWORKS: 1
      SERVICES: 1
      TASKS: 1
    # dockersocketproxy doesn't support syslog
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    image: tecnativa/docker-socket-proxy
    # Traefik's docker socket access on dedicated bridge network
    networks:
      - dockersocket4traefiknetwork
    ports:
      # Publish on (usual) tcp port
      - 2375
    privileged: true
    userns_mode: "host"
    volumes:
      # Access to socket, read-only for security
      - "/var/run/docker.sock:/var/run/docker.sock"
  
  traefik:
    command:
      # Specify internet access > Port 80
      - "--entrypoints.web.address=:80"
      # Enable logs
      # - "--log.filePath=/var/log/traefik.log"
      - "--log.format=json"
      - "--log.level=DEBUG"
      # Traefik socket access from the proxy container, on the defined port
      - "--providers.docker.endpoint=tcp://dockersocketproxy:2375"
      # Only specified containers exposed on the internet
      - "--providers.docker.exposedbydefault=false"
      # Tell Traefik to get the contents provided by this service using a dedicated shared attachable overlay network.
      - "--providers.docker.network=traefik-public"
      # Enable docker swarm
      - "--providers.docker.swarmMode=true"
      # TODO:
      # "traefik.http.routers.helloworld.entrypoints=web"  ????
    depends_on:
      - dockersocketproxy
    # Traefik 2.2
    image: "traefik:chevrotin"
    # Traefik doesn't support syslog
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    networks:
      # Traefik's docker socket access on dedicated network
      - dockersocket4traefiknetwork
      # Traefik access to web server containers, to allow reverse proxy serving
      - traefik-public
    ports:
      - "80:80"
      # - "443:443"
    # Assign the_docker_peon unprivileged user
    # user: 1003:1003
    # read-only

networks:
  dockersocket4traefiknetwork:
    # Prevent access to this network from other containers
    attachable: false

  # Needs to be created before using docker compose
  #   In order to:
  #   - be accessible to futur stacks
  #   - have a set name without automatic prefix
  # > docker network create --driver=overlay --attachable traefik-public
  traefik-public:
    # Connect to an existing network
    external: true