version: "3.7"

# Issues & fixes
#   Access to docker socket is a security risk
#   > Grant access through a proxy container
#   > Socket access with read-only volume

#   Privileged is mandatory to access docker socket, and is also a security risk
#   > Only the proxy container is privileged
#     Priviledged incompatible with user namespace remap.
#     > Force disable user namespace remap on proxy
#       userns_mode: "host" not compatible with docker stack
#       > Will be used through docker compose
#       > Also enable the use of a bridge network

#   Stack only allow overlay networks > security risk
#   > Use docker compose for Traefik & proxy, and set a custom bridge network
#     > non attachable
#     TODO: > encrypted

services:
  dockersocketproxy:
    environment:
      # Authorize access
      NETWORKS: 1
      SERVICES: 1
      TASKS: 1
    image: tecnativa/docker-socket-proxy
    labels:
      fr.masamune.client: 'masamune'
      fr.masamune.maintainer: 'masamune.code@gmail.com'
      fr.masamune.project: 'docker socket proxy'
      fr.masamune.type: 'core'
    # dockersocketproxy doesn't support syslog
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    # Traefik's docker socket access on dedicated bridge network
    networks:
      - dockersocket4traefiknetwork
    ports:
      # Publish on (usual) tcp port
      - 2375
    privileged: true
    security_opt:
      - no-new-privileges:true
      - apparmor=docker-default
      - seccomp=/etc/docker/seccomp-profiles/default-docker-profile.json
    userns_mode: "host"
    volumes:
      # Access to socket, read-only for security
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  
  traefik:
    cap_add:
      - CAP_NET_BIND_SERVICE
    cap_drop:
      - ALL
    command:
      # Specify internet access > Port 80
      - "--entrypoints.web.address=:80"
      # - "--entryPoints.websecure.address=:443"
      # Send Traefik anonymous usage data / https://docs.traefik.io/contributing/data-collection/
      - "--global.sendAnonymousUsage"
      # Enable logs
      # - "--log.filePath=/var/log/traefik.log"
      - "--log.format=json"
      - "--log.level=DEBUG"
      # Allow pings, for healthchecks
      - "--ping=true"
      # Traefik socket access from the proxy container, on the defined port
      - "--providers.docker.endpoint=tcp://dockersocketproxy:2375"
      # Only specified containers exposed on the internet
      - "--providers.docker.exposedbydefault=false"
      # Tell Traefik to get the contents provided by this service using a dedicated shared attachable overlay network.
      - "--providers.docker.network=traefik-public"
      # Enable docker swarm
      - "--providers.docker.swarmMode=true"
    depends_on:
      - dockersocketproxy
    healthcheck:
      test: 'traefik healthcheck --ping'
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 0s
    # Traefik 2.2
    image: "traefik:chevrotin"
    # Traefik doesn't support syslog
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    networks:
      # Traefik's docker socket access on dedicated network
      - dockersocket4traefiknetwork
      # Traefik access to web server containers, to allow reverse proxy serving
      - traefik-public
    ports:
      - "80:80"
      # - "443:443"
    # Assign the_docker_peon unprivileged user
    user: 1003:1003
    # Specific unprivileged user needs access to ports < 1024
    sysctls:
      net.ipv4.ip_unprivileged_port_start: 0
    read_only: true

networks:
  dockersocket4traefiknetwork:
    # Prevent access to this network from other containers
    attachable: false
    # Force default driver as it will be used from docker compose, exclusively for proxy & traefik
    driver: bridge
    driver_opts:
      # Since we're passing docker socket stuff over TCP, lets IPSec
      encrypted: 'true'

  # Needs to be created before using docker compose
  #   In order to:
  #   - be accessible to futur stacks
  #   - have a set name without automatic prefix
  # > docker network create --driver=overlay --attachable traefik-public
  traefik-public:
    # Connect to an existing network
    external: true