version: '3.7'

# http://geekyplatypus.com/dockerise-your-php-application-with-nginx-and-php7-fpm/
services:
  web:
    # latest when writing
    image: nginx:1.17.6-alpine
    networks:
      - network-php
    ports:
      - '8080:80'
    volumes:
      # Project files, bind mount for dev (allow files updates on refresh)
      - type: bind
        source: ./src
        # Custom src path in container
        # Nginx custom conf in HOST/config/nginx1.17.6-alpine/sites-enabled/site.conf
        target: /home/www
      # Replace nginx default conf with blank file to prevent localhost:80 conflict
      - type: bind
        source: ./config/nginx1.17.6-alpine/etc/nginx/conf.d/default.conf
        target: /etc/nginx/conf.d/default.conf
      # Config override
      # Autommatically loaded thanks to default nginx.conf > 'include /etc/nginx/conf.d/*.conf;'
      - type: bind
        source: ./config/nginx1.17.6-alpine/etc/nginx/conf.d/site.conf
        target: /etc/nginx/conf.d/site.conf
  
  phpfpm:
    # latest when writing
    image: 'php:7.4.1-fpm'
    networks:
      - network-php
    volumes:
      # Project files, bind mount for dev
      # Php-fpm needs access to sources files to, else he can't access them due to containerisation
      - type: bind
        source: ./src
        target: /home/www
  
  db:
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: pizza
    # latest when writing
    image: 'mysql:8.0.18'
    restart: always
    #secrets:
    #- MYSQL_ROOT_PASSWORD
    volumes:
      # Autommatically loaded thanks to default my.cnf > '!includedir /etc/mysql/conf.d/'
      - type: bind
        source: ./config/mysql8.0.18/_defaults/etc/mysql/conf.d/my-conf.cnf
        target: /etc/mysql/conf.d/my-conf.cnf
  
  adminer:
    # latest when writing
    image: 'adminer:4.7.5'
    ports:
      # Running on port 8081 as 8080 is already used by web
      - 8081:8080
      
networks:
  network-php:

#secrets:
#  MYSQL_ROOT_PASSWORD:
#    file: ./secrets/mysql/MYSQL_ROOT_PASSWORD.txt