version: '3.7'
services:
  helloworld:
    image: tutum/hello-world:latest
    networks:
      - traefik-public
    deploy:
      labels:
        - "traefik.http.services.helloworld.loadbalancer.server.port=80"
        - "traefik.enable=true"
        

        # Pas vu
        - "traefik.http.routers.helloworld.rule=Host(`hello.localhost`)"
        - "traefik.http.routers.helloworld.entrypoints=web"

networks:
  traefik-public:
    external: true