# https://docs.traefik.io/providers/docker/
# https://creekorful.me/how-to-install-traefik-2-docker-swarm/
version: '3.7'

services:
  traefik:
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - "--providers.docker.swarmMode=true"
      ##  Default="unix:///var/run/docker.sock", lié via le volume
      #- "--providers.docker.endpoint=unix:///var/run/docker.sock"
      #- "--providers.docker.endpoint=tcp://127.0.0.1:2375"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik-public"

      # Désactiver https
      - "--serversTransport.insecureSkipVerify=true"

      - "--entrypoints.web.address=:80"
    
    deploy:
      placement:
        constraints:
          - node.role == manager
    # latest when writing
    image: traefik:v2.1.1
    networks:
      - traefik-public
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      #- "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # So that Traefik can listen to the Docker events
      #- type: bind
      #  source: /var/run/docker.sock
      #  target: /var/run/docker.sock

# Needs 
#   docker network create --driver=overlay traefik-public
# before
networks:
  traefik-public:
    external: true