version: '3.7'
services:
  helloworld:
    deploy:
      labels:
        - "traefik.docker.network=traefik-public"
        - "traefik.enable=true"
        # http://hello.localhost/
        - "traefik.http.routers.helloworld.rule=Host(`hello.localhost`)"
        - "traefik.http.services.helloworld.loadbalancer.server.port=80"
      replicas: 3
    image: tutum/hello-world:latest
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true